const SERVICE_IDS = {
  CAR_ACCIDENT_REPAIR: "car-accident-repair",
  CAR_AUCTION_REPAIR: "car-auction-repair",
  COMPUTER_DIAGNOSTICS: "computer-diagnostics",
  ELECTRONICS: "electronics",
  ENDOSCOPE: "endoscope",
  SUSPENSION_DIAGNOSTICS: "suspension-diagnostics",
  SUSPENSION_REPAIR: "suspension-repair",
  TUNING: "tuning",
}

export const SERVICE_IDS_ORDER = [
  SERVICE_IDS.COMPUTER_DIAGNOSTICS,
  SERVICE_IDS.SUSPENSION_DIAGNOSTICS,
  SERVICE_IDS.ENDOSCOPE,
  SERVICE_IDS.SUSPENSION_REPAIR,
  SERVICE_IDS.CAR_ACCIDENT_REPAIR,
  SERVICE_IDS.CAR_AUCTION_REPAIR,
  SERVICE_IDS.ELECTRONICS,
  SERVICE_IDS.TUNING,
]

export default SERVICE_IDS
